# Generated by Django 4.1.7 on 2023-08-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_product_price_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(error_messages={'unique': 'This URL is already scraped.'}, max_length=500, unique=True),
        ),
    ]
