# Generated by Django 4.1.7 on 2023-08-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(error_messages={'unique': 'This URL is already scraped.'}, max_length=5000, unique=True),
        ),
    ]
